"""add users table

Revision ID: 0799d19450b3
Revises: c7a3e91b45f2
Create Date: 2026-08-04 14:02:21.577830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0799d19450b3'
down_revision: Union[str, Sequence[str], None] = 'c7a3e91b45f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), server_default='free', nullable=False),
    sa.Column('live_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('upload_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('welcomed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_clerk_user_id'), ['clerk_user_id'], unique=True)

    # Autogenerate also proposed dropping classes.voice_name. That column exists
    # in the database but not in models.py — a leftover from the abandoned
    # voice/class split — and dropping it here would rebuild the classes table
    # for a reason that has nothing to do with adding users. Left alone
    # deliberately; removing it is its own decision.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_clerk_user_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
