"""voice picker: add hidden flag; class_id FK RESTRICT

Revision ID: 0d5014d312aa
Revises: 85ce5a858729
Create Date: 2026-07-27 16:21:18.035930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5014d312aa'
down_revision: Union[str, Sequence[str], None] = '85ce5a858729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sessions_class_id_classes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sessions_class_id_classes'), 'classes', ['class_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sessions_class_id_classes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sessions_class_id_classes'), 'classes', ['class_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
