"""user_id becomes a foreign key to users

Revision ID: 63c3f2386827
Revises: 0799d19450b3
Create Date: 2026-08-04 15:32:06.416460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c3f2386827'
down_revision: Union[str, Sequence[str], None] = '0799d19450b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_classes_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_classes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        # voice_name deliberately left alone — see the users migration

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sessions_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sessions_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classes_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_classes_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
