"""rename classes to voices, and sessions.class_id to voice_id

Revision ID: 8f2b1c4d9a07
Revises: 1dc88ee6cee5
Create Date: 2026-08-06 23:05:00.000000

Written by hand rather than autogenerated. Autogenerate compares the models to
the database and sees a table that vanished and one that appeared, so it offers
to DROP classes and CREATE voices — which would take the embeddings with it.
A rename keeps the rows.

Nothing moves. `classes` already held enrolled speakers, and `sessions.class_id`
already pointed at one, so this only makes the names say what the columns were
already doing. `classes.voice_name` goes with it: it existed to give that row a
second name because one column was serving two purposes, and the purposes are
now separate rows. It is empty in every database it exists in.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2b1c4d9a07'
down_revision: Union[str, Sequence[str], None] = '1dc88ee6cee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.rename_table('classes', 'voices')

    # voice_name only exists in databases that ran feature/class-voice-name, so
    # it is dropped conditionally rather than assumed.
    cols = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("voices")}
    if "voice_name" in cols:
        with op.batch_alter_table('voices', schema=None) as batch_op:
            batch_op.drop_column('voice_name')

    # SQLite rewrites the table to rename a column, and the rewrite is where the
    # foreign key is re-pointed at `voices` — batch_alter_table is what makes
    # both survive on a database that cannot ALTER a constraint in place.
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('class_id', new_column_name='voice_id')


def downgrade() -> None:
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('voice_id', new_column_name='class_id')

    with op.batch_alter_table('voices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_name', sa.String(), nullable=True))

    op.rename_table('voices', 'classes')
