"""
ClassRec — ORM models (the tables, as Python classes)
=====================================================

This REPLACES the hand-written CREATE TABLE SQL. Each class = one table;
each attribute = one column. SQLAlchemy reads these to generate the SQL.

Two tables, same as before:
    Class    — a class + its ONE professor voice embedding
    Session  — one lecture transcript, linked to its class
"""

from __future__ import annotations

import datetime

from sqlalchemy import Boolean, ForeignKey, Integer, LargeBinary, MetaData, String, Text, Float, DateTime, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


# Production best-practice: give every constraint a deterministic NAME. SQLite
# leaves constraints unnamed, which breaks Alembic migrations that try to alter
# them ("Constraint must have a name"). This convention fixes that everywhere.
NAMING_CONVENTION = {
    "ix":  "ix_%(column_0_label)s",
    "uq":  "uq_%(table_name)s_%(column_0_name)s",
    "ck":  "ck_%(table_name)s_%(constraint_name)s",
    "fk":  "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk":  "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """All models inherit from this. It's the registry the ORM uses to know
    about every table when creating them / generating migrations."""
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class User(Base):
    """One row per person, created the first time we see them.

    Clerk owns the identity — email, name, password, Google — and this table owns
    only what is ours: what they are allowed to do and what they have used.

    Two ids on purpose. `id` is ours and is what every other table references, so
    lectures and voices hold a normal integer foreign key like the rest of the
    schema. `clerk_user_id` is Clerk's ("user_2abc…") and is quarantined to this
    one column: it is generated by a system we do not run, cannot be enforced by
    the database, and would have to be rewritten everywhere if we ever left
    Clerk. Here it is a single indexed lookup instead.

    Email and name are deliberately absent. They live in Clerk, and a copy here
    goes stale the moment someone changes them.
    """
    __tablename__ = "users"

    id:            Mapped[int]         = mapped_column(primary_key=True)
    # unique: one row per Clerk account. indexed because every authenticated
    # request resolves this to `id`.
    clerk_user_id: Mapped[str]         = mapped_column(String, unique=True, index=True)
    # 'free' today; the only other value will be whatever paid becomes.
    plan:          Mapped[str]         = mapped_column(String, default="free", server_default="free")
    # Usage in seconds, not minutes: minutes were a float in localStorage and
    # accumulated rounding. Integers add exactly.
    live_seconds:   Mapped[int]        = mapped_column(Integer, default=0, server_default="0")
    upload_seconds: Mapped[int]        = mapped_column(Integer, default=0, server_default="0")
    # Set once the welcome email has gone out, so a re-login does not send it again.
    welcomed_at:   Mapped[datetime.datetime | None] = mapped_column(DateTime)
    created_at:    Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now())


class Class(Base):
    __tablename__ = "classes"                       # -> CREATE TABLE classes

    # id INTEGER PRIMARY KEY (auto)
    id:         Mapped[int]               = mapped_column(primary_key=True)
    # user_id -> users.id. Nullable: rows predating accounts have no owner, and
    # they stay that way. ON DELETE CASCADE so deleting an account takes its
    # voices with it — required for "delete my data" to mean anything.
    user_id:    Mapped[int | None]        = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    # name TEXT NOT NULL  (Mapped[str] without "| None" = NOT NULL)
    name:       Mapped[str]               = mapped_column(String)
    # embedding BLOB (nullable) — LargeBinary is SQLAlchemy's word for BLOB
    embedding:  Mapped[bytes | None]      = mapped_column(LargeBinary)
    # audio_path — where the enrollment clip is stored on disk, for playback
    audio_path: Mapped[str | None]        = mapped_column(String)
    # threshold REAL DEFAULT 0.4
    threshold:  Mapped[float]             = mapped_column(Float, default=0.4)
    # use_count — bumped each time this Voice records a lecture; powers "top 4 most used".
    # server_default="0" so existing rows get 0 when this column is added by migration.
    use_count:  Mapped[int]               = mapped_column(Integer, default=0, server_default="0")
    # hidden — the 🗑️ in the picker sets this True (remove from list, keep the data
    # so linked Lectures still show their Voice). Hard-delete only once no Lecture uses it.
    hidden:     Mapped[bool]              = mapped_column(Boolean, default=False, server_default="0")
    # created_at — server_default=now() lets the DB fill it in
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now())

    # One Voice has many Lectures. passive_deletes=True -> let the DB's ON DELETE
    # SET NULL handle it (deleting a Voice does NOT delete its Lectures; they just
    # lose their class link). No delete-orphan cascade anymore.
    sessions: Mapped[list["Session"]] = relationship(
        back_populates="course", passive_deletes=True
    )


class Session(Base):
    __tablename__ = "sessions"                      # -> CREATE TABLE sessions

    id:         Mapped[int]               = mapped_column(primary_key=True)
    # class_id FK -> classes.id. Nullable (a Lecture MAY have no Voice), but if it
    # has one the link is permanent. ON DELETE RESTRICT: the DB blocks deleting a
    # Voice while any Lecture still references it (so the link is never lost).
    class_id:   Mapped[int | None]        = mapped_column(
        ForeignKey("classes.id", ondelete="RESTRICT")
    )
    user_id:    Mapped[int | None]        = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    title:      Mapped[str]               = mapped_column(String)
    transcript: Mapped[str | None]        = mapped_column(Text)
    summary:    Mapped[str | None]        = mapped_column(Text)
    words_json: Mapped[str | None]        = mapped_column(Text)
    audio_path: Mapped[str | None]        = mapped_column(String)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now())

    # The other side of the relationship: each Session points back to its Class.
    # Named "course" (not "class") because `class` is a reserved word in Python.
    course: Mapped["Class"] = relationship(back_populates="sessions")

    # A Lecture owns its Flags. delete-orphan + passive_deletes lets the DB's
    # ON DELETE CASCADE do the work — important because the 7-lecture cap in
    # repository.save_session evicts old Sessions, and their Flags must go too.
    flags: Mapped[list["Flag"]] = relationship(
        back_populates="lecture", cascade="all, delete-orphan", passive_deletes=True,
        order_by="Flag.t_start",
    )


class Flag(Base):
    """A moment the student didn't follow.

    Raised live, mid-lecture, by selecting a span of the transcript. Because a
    Session row doesn't exist until the user hits save, Flags are collected in
    the page and written as part of that same save — hence session_id is NOT
    NULL and there is no half-attached state to reconcile.
    """

    __tablename__ = "flags"

    id:         Mapped[int]               = mapped_column(primary_key=True)
    session_id: Mapped[int]               = mapped_column(
        ForeignKey("sessions.id", ondelete="CASCADE"), index=True
    )
    # Seconds from the start of the recording — absolute, because transcribe_chunk
    # already folds chunk_offset into every word's start/end before sending it.
    t_start:    Mapped[float]             = mapped_column(Float)
    t_end:      Mapped[float]             = mapped_column(Float)
    # The selected words, verbatim. Stored rather than re-derived so a flag still
    # reads correctly if the transcript is ever re-processed.
    quote:      Mapped[str]               = mapped_column(Text)
    # Both nullable: flagging a moment is one tap and does NOT require asking
    # anything. A bare flag ("come back to this") is a valid end state.
    question:   Mapped[str | None]        = mapped_column(Text)
    answer:     Mapped[str | None]        = mapped_column(Text)
    resolved:   Mapped[bool]              = mapped_column(Boolean, default=False,
                                                          server_default="0")
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=func.now())

    lecture: Mapped["Session"] = relationship(back_populates="flags")
